project.git = true
version = 3.0.0-RC6
maxColumn = 120
docstrings.style = Asterisk

align.tokens = ["%", "%%", {code = "=>", owner = "Case"}]
align.openParenCallSite = false
align.openParenDefnSite = false
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
danglingParentheses.preset = true
