name: Submit Dependency Graph

on:
  push:
    branches:
      - develop

jobs:
  submit-graph:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write # this permission is needed to submit the dependency graph
    steps:
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1.5.8

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Submit Dependency Graph
        uses: scalacenter/sbt-dependency-graph-action@d84eef4c09e633bcf5f113bcad7fd5e9af1baee9 # v3.2.3
