name: Release

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v7

    - name: Set up JDK
      uses: actions/setup-java@v6.0.0
      with:
        java-version: 17
        distribution: temurin

    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1.5.8

    - name: Build plugin
      run: sbt assembly

    - name: Create Release
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        files: target/scala-2.13/gitbucket-navlink-plugin-*.jar
