name: Scala CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Run Docker containers
      run: docker-compose up -d

    - name: Build
      run: sbt scalafmtSbtCheck scalafmtCheck
